# Generated by scripts/update-formula.sh from the v0.1.9 release. Don't edit by hand.
class Quietmouse < Formula
  desc "Offline, telemetry-free settings, buttons and gestures for Logitech mice"
  homepage "https://github.com/benjweaver/quietmouse"
  license "MIT"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  # One universal archive serves both Apple Silicon and Intel Macs.
  on_macos do
    on_arm do
      url "https://github.com/benjweaver/quietmouse/releases/download/v0.1.9/quietmouse-v0.1.9-macos-universal.tar.gz"
      sha256 "536b25e0c0c8ae88782a8ba816efc3a78b3ea5dcfa3e9846601eee2f7bcc3bac"
    end
    on_intel do
      url "https://github.com/benjweaver/quietmouse/releases/download/v0.1.9/quietmouse-v0.1.9-macos-universal.tar.gz"
      sha256 "536b25e0c0c8ae88782a8ba816efc3a78b3ea5dcfa3e9846601eee2f7bcc3bac"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/benjweaver/quietmouse/releases/download/v0.1.9/quietmouse-v0.1.9-linux-x86_64.tar.gz"
      sha256 "0c1fdf724d92f8a2a685b6d210cf4f9f2b46b138683b1d732fb4549616f00b46"
    end
  end

  def install
    bin.install "quietmouse", "quietmoused"
    pkgshare.install Dir["**/70-quietmouse.rules", "**/modules-load.conf"] if OS.linux?
    # Releases before 0.1.9 don't carry the notices.
    doc.install "THIRD-PARTY-NOTICES.md" if File.exist?("THIRD-PARTY-NOTICES.md")
  end

  def caveats
    message = <<~TEXT
      Write a config, then start quietmouse now and whenever you log in:
        quietmouse config --init
        quietmouse autostart on
    TEXT
    if OS.mac?
      message + <<~TEXT

        On macOS, quietmouse asks for Input Monitoring and Accessibility (called
        Device Control and Data Access on newer macOS) when the agent starts, so
        macOS prompts and lists it ready to switch on.

        After upgrading, run "quietmouse autostart on" to point at the new
        version, then switch quietmoused on in both lists when macOS asks.
        Permissions are tied to the exact binary, so each version asks again.
      TEXT
    else
      message + <<~TEXT

        On Linux, install the udev rule once so your user can open Logitech devices:
          sudo install -m 644 #{pkgshare}/70-quietmouse.rules /etc/udev/rules.d/
          sudo udevadm control --reload
          sudo udevadm trigger
      TEXT
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/quietmouse --version")
    system bin/"quietmouse", "config", "--init"
    system bin/"quietmouse", "config", "--check"
  end
end
