# Generated by scripts/update-formula.sh from the v0.1.28 release. Don't edit by hand.
class Quietmouse < Formula
  desc "Offline, telemetry-free settings, buttons and gestures for Logitech mice"
  homepage "https://github.com/benjweaver/quietmouse"
  license "GPL-3.0-or-later"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  # One universal archive serves both Apple Silicon and Intel Macs.
  on_macos do
    on_arm do
      url "https://github.com/benjweaver/quietmouse/releases/download/v0.1.28/quietmouse-v0.1.28-macos-universal.tar.gz"
      sha256 "d7402cc575bc9baef5a4c3c0a7530d2acd4d99e53ea428c6a7692c7b443267f1"
    end
    on_intel do
      url "https://github.com/benjweaver/quietmouse/releases/download/v0.1.28/quietmouse-v0.1.28-macos-universal.tar.gz"
      sha256 "d7402cc575bc9baef5a4c3c0a7530d2acd4d99e53ea428c6a7692c7b443267f1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/benjweaver/quietmouse/releases/download/v0.1.28/quietmouse-v0.1.28-linux-x86_64.tar.gz"
      sha256 "8dc495a5b8528af807861bfd4866a4c8ad6edfd5fda6e22afbc144d861b04d35"
    end
  end

  def install
    bin.install "quietmouse"
    # On macOS quietmoused's real binary lives inside a minimal .app bundle, so
    # Privacy & Security has a real icon for it under Accessibility and Input
    # Monitoring instead of a generic one; a bare binary has no bundle for those
    # lists to read an icon from. quietmoused itself has to go in as a symlink
    # into the bundle, not the bundle directly: brew link only symlinks
    # individual files out of a keg's bin into the shared bin it puts on PATH,
    # silently skipping whole directories, so the bundle would never reach it.
    # Linux has no such list, so it stays a bare binary there.
    if OS.mac?
      bin.install "quietmoused.app"
      bin.install_symlink "quietmoused.app/Contents/MacOS/quietmoused" => "quietmoused"
    else
      bin.install "quietmoused"
    end
    pkgshare.install Dir["**/70-quietmouse.rules", "**/modules-load.conf"] if OS.linux?
    # Releases before 0.1.9 don't carry the notices.
    doc.install "THIRD-PARTY-NOTICES.md" if File.exist?("THIRD-PARTY-NOTICES.md")
  end

  def caveats
    message = <<~TEXT
      Write a config, then start quietmouse now and whenever you log in:
        quietmouse config --init
        quietmouse autostart on
    TEXT
    if OS.mac?
      message + <<~TEXT

        On macOS, quietmouse asks for Input Monitoring and Accessibility (called
        Device Control and Data Access on newer macOS) when the agent starts, so
        macOS prompts and lists it ready to switch on.

        After upgrading, run "quietmouse autostart on" to point at the new
        version, then switch quietmoused on in both lists when macOS asks. On
        macOS 27 it's listed once, under Device Control and Data Access.
        Permissions are tied to the exact binary, so each version asks again.
      TEXT
    else
      message + <<~TEXT

        On Linux, install the udev rule once so your user can open Logitech devices:
          sudo install -m 644 #{pkgshare}/70-quietmouse.rules /etc/udev/rules.d/
          sudo udevadm control --reload
          sudo udevadm trigger
      TEXT
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/quietmouse --version")
    system bin/"quietmouse", "config", "--init"
    system bin/"quietmouse", "config", "--check"
  end
end
