#!/bin/sh
# Writes Formula/quietmouse.rb for the latest quietmouse release, or for the tag
# given as the first argument, using the checksums published with the release.
# Needs the GitHub CLI (gh).
set -eu

repo=benjweaver/quietmouse
tag=${1:-$(gh release view --repo "$repo" --json tagName -q .tagName)}
sums=$(gh release download "$tag" --repo "$repo" --pattern SHA256SUMS --output -)

checksum() {
    printf '%s\n' "$sums" | awk -v file="$1" '$2 == file { print $1 }'
}
macos=$(checksum "quietmouse-$tag-macos-universal.tar.gz")
linux=$(checksum "quietmouse-$tag-linux-x86_64.tar.gz")
if [ -z "$macos" ] || [ -z "$linux" ]; then
    echo "SHA256SUMS for $tag is missing the macOS or Linux archive" >&2
    exit 1
fi

base="https://github.com/$repo/releases/download/$tag"
cd "$(dirname "$0")/.."
mkdir -p Formula
cat > Formula/quietmouse.rb <<EOF
# Generated by scripts/update-formula.sh from the $tag release. Don't edit by hand.
class Quietmouse < Formula
  desc "Offline, telemetry-free settings, buttons and gestures for Logitech mice"
  homepage "https://github.com/$repo"
  license "MIT"

  livecheck do
    url :homepage
    strategy :github_latest
  end

  # One universal archive serves both Apple Silicon and Intel Macs.
  on_macos do
    on_arm do
      url "$base/quietmouse-$tag-macos-universal.tar.gz"
      sha256 "$macos"
    end
    on_intel do
      url "$base/quietmouse-$tag-macos-universal.tar.gz"
      sha256 "$macos"
    end
  end

  on_linux do
    on_intel do
      url "$base/quietmouse-$tag-linux-x86_64.tar.gz"
      sha256 "$linux"
    end
  end

  def install
    bin.install "quietmouse"
    # On macOS quietmoused lives inside a minimal .app bundle, so Privacy &
    # Security has a real icon for it under Accessibility and Input Monitoring
    # instead of a generic one; a bare binary has no bundle for those lists to
    # read an icon from. Linux has no such list, so it stays a bare binary there.
    if OS.mac?
      bin.install "quietmoused.app"
    else
      bin.install "quietmoused"
    end
    pkgshare.install Dir["**/70-quietmouse.rules", "**/modules-load.conf"] if OS.linux?
    # Releases before 0.1.9 don't carry the notices.
    doc.install "THIRD-PARTY-NOTICES.md" if File.exist?("THIRD-PARTY-NOTICES.md")
  end

  def caveats
    message = <<~TEXT
      Write a config, then start quietmouse now and whenever you log in:
        quietmouse config --init
        quietmouse autostart on
    TEXT
    if OS.mac?
      message + <<~TEXT

        On macOS, quietmouse asks for Input Monitoring and Accessibility (called
        Device Control and Data Access on newer macOS) when the agent starts, so
        macOS prompts and lists it ready to switch on.

        After upgrading, run "quietmouse autostart on" to point at the new
        version, then switch quietmoused on in both lists when macOS asks.
        Permissions are tied to the exact binary, so each version asks again.
      TEXT
    else
      message + <<~TEXT

        On Linux, install the udev rule once so your user can open Logitech devices:
          sudo install -m 644 #{pkgshare}/70-quietmouse.rules /etc/udev/rules.d/
          sudo udevadm control --reload
          sudo udevadm trigger
      TEXT
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/quietmouse --version")
    system bin/"quietmouse", "config", "--init"
    system bin/"quietmouse", "config", "--check"
  end
end
EOF
echo "Formula/quietmouse.rb now points at $tag"
